version: '3.8'

services:
  # mysqldb:
  #   image: mysql:5.7
  #   restart: unless-stopped
  #   env_file: ./.env
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
  #     - MYSQL_DATABASE=$DB_NAME
  #   ports:
  #     - "3308:3306"
  #   volumes:
  #     - db:/var/lib/mysql
  app:
    build: .
    image: "ansibleimg"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "7005:7005"
    environment:
      - DB_HOST=myrdsdb.cpumy6kiu8rd.ap-south-1.rds.amazonaws.com
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true

